imports:
    - https://raw.githubusercontent.com/cloudify-cosmo/cloudify-openstack-plugin/develop/plugin.yaml
    - https://raw.githubusercontent.com/cloudify-cosmo/cloudify-puppet-plugin/develop/plugin.yaml

blueprint:
    name: system-test-puppet-db
    nodes:
        -   name: db-vm
            type: cloudify.openstack.server
            properties:
                install_agent: true
                management_network_name: REPLACED-BY-TEST
                server:
                    name: REPLACED-BY-TEST
                    image_name: REPLACED-BY-TEST
                    flavor_name: REPLACED-BY-TEST
                    key_name: REPLACED-BY-TEST
                    security_groups: [puppet_sg]  # MODIFIED-BY-TEST (adds agents security group to the list)
                    # MODIFIED-BY-TEST -- {hostname} substitution
                    userdata: |
                        #!/bin/bash -ex
                        grep -q puppet /etc/hosts || echo "{puppet_server_ip} puppet" >> /etc/hosts
            relationships:
                -   type: cloudify.openstack.server_connected_to_floating_ip
                    target: ip
        -   name: puppet_db
            type: cloudify.types.puppet.db_server
            properties:
                puppet_config:
                    add_operation_tag: True,
                    operations_tags:
                        create: [op_tag_create, tag2]
                    environment: e1
                    tags: [a, b]
                    server: puppet
                    node_name_prefix: pfx-
                    node_name_suffix: .puppet.example.com
            relationships:
                -   type: cloudify.relationships.contained_in
                    target: db-vm

        -   name: ip
            type: cloudify.openstack.floatingip
            properties:
                floatingip:
                    floating_network_name: REPLACED-BY-TEST
