imports:
    - http://www.getcloudify.org/spec/openstack-plugin/1.0/plugin.yaml
    - http://www.getcloudify.org/spec/puppet-plugin/1.0/plugin.yaml

types:
    cloudify.types.puppet.puppet_master_service:
        derived_from: cloudify.types.middleware_server
        properties:
            - puppet_config
        interfaces:
            cloudify.interfaces.lifecycle:
                - create: puppet_plugin.install.operation

blueprint:
    name: system-test-puppet-master
    nodes:
        -   name: puppet_master_vm
            type: cloudify.openstack.server
            properties:
                install_agent: true
                management_network_name: REPLACED-BY-TEST
                server:
                    name: REPLACED-BY-TEST
                    image_name: REPLACED-BY-TEST
                    flavor_name: REPLACED-BY-TEST
                    key_name: REPLACED-BY-TEST
                    security_groups: [puppet_sg]  # MODIFIED-BY-TEST (adds agents security group to the list)
                    # MODIFIED-BY-TEST -- {hostname} substitution
                    userdata: |
                        #!/bin/bash -ex
                        grep -q "{hostname}" /etc/hosts || echo "127.0.0.1 {hostname}" >> /etc/hosts
            relationships:
                -   type: cloudify.openstack.server_connected_to_floating_ip
                    target: ip
                -   type: cloudify.relationships.connected_to
                    target: puppet_sg
        -   name: ip
            type: cloudify.openstack.floatingip
            properties:
                floatingip:
                    floating_network_name: REPLACED-BY-TEST
        -   name: puppet_sg
            type: cloudify.openstack.security_group
            properties:
                security_group:
                    name: puppet_sg
                rules:
                    -   remote_ip_prefix: 0.0.0.0/0
                        port: 22
                    -   remote_ip_prefix: 0.0.0.0/0
                        port: 8140
        -   name: system_tests_puppet_master_service
            type: cloudify.types.puppet.puppet_master_service
            properties:
                puppet_config:
                    server: puppet
                    environment: cloudify0system0test
            relationships:
                -   type: cloudify.relationships.contained_in
                    target: puppet_master_vm

