sudo: false
language: python
python:
  - "2.7"

install:
    - pip install flake8
    - pip install -r test-requirements.txt
    - pip install .
    - echo "" > docker && chmod +x docker
    - echo "" > vagrant && chmod +x vagrant
    - export PATH=$PATH:$(pwd)

script:
    - flake8 .
    - nosetests suites/tests
