connection:
    cloud_provider_name: "ec2_us_east"
    access_id: ''
    secret_key: ''

networking:
    agents_security_group:
        create_if_missing: true
        name: systemt-adaml-cloudify-sg-agents
    management_security_group:
        create_if_missing: true
        name: systemt-adaml-cloudify-sg-management
        cidr: 0.0.0.0/0

compute:
    management_server:
        floating_ip:
            create_if_missing: true
#            ip: ENTER-PUBLIC-IP-HERE
        user_on_management: ubuntu
        userhome_on_management: /home/ubuntu
        instance:
            create_if_missing: true
            name: systemt-adaml-cloudify-management-server
            image: "ami-fa7dba92"
            size: "m1.medium"
        management_keypair:
            create_if_missing: true
            name: systemt-adaml-cloudify-management-kp
            private_key_path: ~/.ssh/systemt-adaml-cloudify-management-kp.pem
    agent_servers:
        agents_keypair:
            create_if_missing: true
            name: systemt-adaml-cloudify-agents-kp
            private_key_path: ~/.ssh/systemt-adaml-cloudify-agents-kp.pem

cloudify:
    # Currently not implemented for ec2
    #resources_prefix: 'systemt-adaml'
    server:
        packages:
            components_package_url: http://gigaspaces-repository-eu.s3.amazonaws.com/org/cloudify3/3.1.0/m3-RELEASE/cloudify-components_3.1.0-m3-b80_amd64.deb
            core_package_url: http://gigaspaces-repository-eu.s3.amazonaws.com/org/cloudify3/3.1.0/m3-RELEASE/cloudify-core_3.1.0-m3-b80_amd64.deb
            ui_package_url: http://gigaspaces-repository-eu.s3.amazonaws.com/org/cloudify3/3.1.0/m3-RELEASE/cloudify-ui_3.1.0-m3-b80_amd64.deb
    agents:
        packages:
            ubuntu_agent_url: http://gigaspaces-repository-eu.s3.amazonaws.com/org/cloudify3/3.1.0/m3-RELEASE/cloudify-ubuntu-agent_3.1.0-m3-b80_amd64.deb
            centos_agent_url: http://gigaspaces-repository-eu.s3.amazonaws.com/org/cloudify3/3.1.0/m3-RELEASE/cloudify-centos-agent_3.1.0-m3-b80_amd64.deb
            windows_agent_url: http://gigaspaces-repository-eu.s3.amazonaws.com/org/cloudify3/3.1.0/m3-RELEASE/cloudify-windows-agent_3.1.0-m3-b80_amd64.deb
        config:
            min_workers: 2
            max_workers: 5
            remote_execution_port: 22
            user: ubuntu
    workflows:
        task_retries: 20
        retry_interval: 30

    bootstrap:
        ssh:
            initial_connectivity_retries: 20
            initial_connectivity_retries_interval: 15
            command_retries: 3
            retries_interval: 3
            connection_attempts: 20
agents:
    config:
        user: ubuntu