
imports:
    - https://raw.githubusercontent.com/cloudify-cosmo/cloudify-manager/develop/resources/rest-service/cloudify/types/types.yaml

blueprint:
    name: single_node
    nodes:
        -   name: mock_vm
            type: cloudify.types.base
