imports:
    - https://raw.githubusercontent.com/cloudify-cosmo/cloudify-openstack-plugin/develop/plugin.yaml

plugins:
    python_script_executor:
        derived_from: cloudify.plugins.agent_plugin
        properties:
            url: https://github.com/cloudify-cosmo/cloudify-python-plugin/archive/1.0-m4.zip

types:
    cloudify.types.python.app_module:
        derived_from: cloudify.types.app_module
        interfaces:
            cloudify.interfaces.lifecycle:
                - start: python_script_executor.tasks.run
        properties:
            - scripts

blueprint:
    name: centos-test
    nodes:
        -   name: vm
            type: cloudify.openstack.server
            properties:
                server:
                    name: centos-agent-vm
                    image: 202e7659-f7c6-444a-8b32-872fe2ed080c
                    flavor: 102
                cloudify_agent:
                    user: root

        -   name: app
            type: cloudify.types.python.app_module
            properties:
                scripts:
                    start: scripts/hello.py
            relationships:
                -   type: cloudify.relationships.contained_in
                    target: vm