keystone:
    username: <user>
    password: <pass>
    tenant_name: <tenant>
    auth_url: https://region-b.geo-1.identity.hpcloudsvc.com:35357/v2.0/

networking:
    neutron_supported_region: true
    neutron_url: https://region-b.geo-1.network.hpcloudsvc.com
    int_network:
        use_existing: false
        name: cloudify-admin-network
    subnet:
        use_existing: false
        name: cloudify-admin-network-subnet
        ip_version: 4
        cidr: 10.67.80.0/24

    ext_network:
        use_existing: true 
        name: Ext-Net
    router:
        use_existing: false
        name: cloudify-router
    agents_security_group:
        use_existing: false
        name: cloudify-sg-agents
    management_security_group:
        use_existing: false
        name: cloudify-sg-management
        cidr: 0.0.0.0/0

compute:
    region: region-b.geo-1
    management_server:
        #floating_ip: [FLOATING_IP] #uncomment and provide preallocated ip to disable auto-allocation of new IP on each run
        user_on_management: ubuntu
        userhome_on_management: /home/ubuntu
        instance:
            use_existing: false
            name: cloudify-management-server
            image: fc369a68-65c6-4bad-8786-dfd5769cff0a
            flavor: 102
        management_keypair:
            use_existing: false
            name: cloudify-management-kp
            private_key_path: ~/.ssh/cloudify-management-kp.pem
    agent_servers:
        agents_keypair:
            use_existing: false
            name: cloudify-agents-kp
            private_key_path: ~/.ssh/cloudify-agents-kp.pem

