imports:
    - https://raw.githubusercontent.com/cloudify-cosmo/cloudify-manager/develop/resources/rest-service/cloudify/types/types.yaml

plugins:
    mock_plugin:
        derived_from: cloudify.plugins.manager_plugin
        properties:
            folder: mock-plugin

types:
    host:
        derived_from: cloudify.types.host
        interfaces:
            cloudify.interfaces.lifecycle:
                - create: mock_plugin.mock.create
                - configure: mock_plugin.mock.configure
                - start: mock_plugin.mock.start
                - stop: mock_plugin.mock.stop
                - delete: mock_plugin.mock.delete
            cloudify.interfaces.host:
                - get_state: mock_plugin.mock.get_state

    middle:
        derived_from: cloudify.types.middleware_server
        interfaces:
            cloudify.interfaces.lifecycle:
                - create: mock_plugin.mock.create
                - configure: mock_plugin.mock.configure
                - start: mock_plugin.mock.start
                - stop: mock_plugin.mock.stop
                - delete: mock_plugin.mock.delete

relationships:
    contained_in:
        derived_from: cloudify.relationships.contained_in
        source_interfaces:
            cloudify.interfaces.relationship_lifecycle:
                - preconfigure: mock_plugin.mock.preconfigure
                - postconfigure: mock_plugin.mock.postconfigure
                - establish: mock_plugin.mock.establish
                - unlink: mock_plugin.mock.unlink

    connected_to:
        derived_from: cloudify.relationships.connected_to
        source_interfaces:
            cloudify.interfaces.relationship_lifecycle:
                - preconfigure: mock_plugin.mock.preconfigure
                - postconfigure: mock_plugin.mock.postconfigure
                - establish: mock_plugin.mock.establish
                - unlink: mock_plugin.mock.unlink

blueprint:
    name: many_instances
    nodes:
        -   name: host
            type: host
            instances:
                deploy: 100
            properties:
                install_agent: false
        -   name: middle
            type: middle
            instances:
                deploy: 1
            relationships:
                -   type: contained_in
                    target: host
        -   name: middle2
            type: middle
            instances:
                deploy: 100
            relationships:
                -   type: connected_to
                    target: middle
                    properties:
                        connection_type: all_to_one
