#######
# Cloudify Hello World blueprint.
#
# The blueprint describes a vSphere vm created using Cloudify's vSphere Plugin
# and simple web server started using Cloudify's bash plugin.
#

imports:
    - http://www.getcloudify.org/spec/bash-plugin/1.0/plugin.yaml
    - http://tarzan/users/boris/temp/cloudify-vsphere-plugin-1-develop/plugin.yaml

types:
    # A web server configured with bash scripts
    cloudify.types.bash.web_server_with_index_and_image:
        derived_from: cloudify.types.bash.web_server
        properties:
            - image_path
            - index_path

# The blueprint contains two nodes, a vm and a web server hosted in it.
blueprint:
    name: hello_world
    nodes:
        -   name: vm
            type: cloudify.vsphere.server
            instances:
                deploy: 1
            properties:
                cloudify_agent:
                    user: giga
                networking:
                    use_dhcp: True
                    switch_distributed: True
                    management_network:
                        name: Management
                    connected_networks: DMZ
                server:
                    name: bash-web-server
                    template: ubuntu-configured-template
                    cpus: 2
                    memory: 3096
                connection_config:
                    datacenter_name: Cloudify-Datacenter
                    resource_pool_name: Resources
                    auto_placement: False

        -   name: http_web_server
            type: cloudify.types.bash.web_server_with_index_and_image
            properties:
                port: 8080
                image_path: images/cloudify-logo.png
                index_path: index.html
                scripts:
                    configure: scripts/configure.sh
                    start: scripts/start.sh
                    stop: scripts/stop.sh
            relationships:
                -   type: cloudify.relationships.contained_in
                    target: vm


